// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `pls.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package top.macaulish.pls.service.ice.client;

import top.macaulish.pls.pojo.ice.*;

public interface TaskPrx extends com.zeroc.Ice.ObjectPrx
{
    default ActionBack create(String modelGuid, String taskGuid, String sourceType, String resultType)
    {
        return create(modelGuid, taskGuid, sourceType, resultType, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ActionBack create(String modelGuid, String taskGuid, String sourceType, String resultType, java.util.Map<String, String> context)
    {
        return _iceI_createAsync(modelGuid, taskGuid, sourceType, resultType, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ActionBack> createAsync(String modelGuid, String taskGuid, String sourceType, String resultType)
    {
        return _iceI_createAsync(modelGuid, taskGuid, sourceType, resultType, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ActionBack> createAsync(String modelGuid, String taskGuid, String sourceType, String resultType, java.util.Map<String, String> context)
    {
        return _iceI_createAsync(modelGuid, taskGuid, sourceType, resultType, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<ActionBack> _iceI_createAsync(String iceP_modelGuid, String iceP_taskGuid, String iceP_sourceType, String iceP_resultType, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ActionBack> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "create", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_modelGuid);
            ostr.writeString(iceP_taskGuid);
            ostr.writeString(iceP_sourceType);
            ostr.writeString(iceP_resultType);
                 }, istr -> {
            ActionBack ret;
            ret = ActionBack.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default ActionBack start(String taskGuid)
    {
        return start(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ActionBack start(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_startAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ActionBack> startAsync(String taskGuid)
    {
        return _iceI_startAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ActionBack> startAsync(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_startAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<ActionBack> _iceI_startAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ActionBack> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "start", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_taskGuid);
                 }, istr -> {
            ActionBack ret;
            ret = ActionBack.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default ActionBack pause(String taskGuid)
    {
        return pause(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ActionBack pause(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_pauseAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ActionBack> pauseAsync(String taskGuid)
    {
        return _iceI_pauseAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ActionBack> pauseAsync(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_pauseAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<ActionBack> _iceI_pauseAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ActionBack> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "pause", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_taskGuid);
                 }, istr -> {
            ActionBack ret;
            ret = ActionBack.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default ActionBack resume(String taskGuid)
    {
        return resume(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ActionBack resume(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_resumeAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ActionBack> resumeAsync(String taskGuid)
    {
        return _iceI_resumeAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ActionBack> resumeAsync(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_resumeAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<ActionBack> _iceI_resumeAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ActionBack> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "resume", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_taskGuid);
                 }, istr -> {
            ActionBack ret;
            ret = ActionBack.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default ActionBack stop(String taskGuid)
    {
        return stop(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ActionBack stop(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_stopAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ActionBack> stopAsync(String taskGuid)
    {
        return _iceI_stopAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ActionBack> stopAsync(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_stopAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<ActionBack> _iceI_stopAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ActionBack> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stop", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_taskGuid);
                 }, istr -> {
            ActionBack ret;
            ret = ActionBack.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default ActionBack delete(String taskGuid)
    {
        return delete(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ActionBack delete(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_deleteAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ActionBack> deleteAsync(String taskGuid)
    {
        return _iceI_deleteAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ActionBack> deleteAsync(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_deleteAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<ActionBack> _iceI_deleteAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ActionBack> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "delete", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_taskGuid);
                 }, istr -> {
            ActionBack ret;
            ret = ActionBack.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default TaskInfo query(String taskGuid)
    {
        return query(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default TaskInfo query(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_queryAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<TaskInfo> queryAsync(String taskGuid)
    {
        return _iceI_queryAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<TaskInfo> queryAsync(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_queryAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<TaskInfo> _iceI_queryAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<TaskInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "query", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_taskGuid);
                 }, istr -> {
            TaskInfo ret;
            ret = TaskInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default TaskProcessInfo getProgress(String taskGuid)
    {
        return getProgress(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default TaskProcessInfo getProgress(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_getProgressAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<TaskProcessInfo> getProgressAsync(String taskGuid)
    {
        return _iceI_getProgressAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<TaskProcessInfo> getProgressAsync(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_getProgressAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<TaskProcessInfo> _iceI_getProgressAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<TaskProcessInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getProgress", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_taskGuid);
                 }, istr -> {
            TaskProcessInfo ret;
            ret = TaskProcessInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default PathInfo getUploadDir(String taskGuid)
    {
        return getUploadDir(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default PathInfo getUploadDir(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_getUploadDirAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<PathInfo> getUploadDirAsync(String taskGuid)
    {
        return _iceI_getUploadDirAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<PathInfo> getUploadDirAsync(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_getUploadDirAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<PathInfo> _iceI_getUploadDirAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<PathInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getUploadDir", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_taskGuid);
                 }, istr -> {
            PathInfo ret;
            ret = PathInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default PathInfo getDownloadDir(String taskGuid)
    {
        return getDownloadDir(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default PathInfo getDownloadDir(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_getDownloadDirAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<PathInfo> getDownloadDirAsync(String taskGuid)
    {
        return _iceI_getDownloadDirAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<PathInfo> getDownloadDirAsync(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_getDownloadDirAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<PathInfo> _iceI_getDownloadDirAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync) {
        com.zeroc.IceInternal.OutgoingAsync<PathInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getDownloadDir", null, sync, null);
        f.invoke(true, context, null, ostr -> {
            ostr.writeString(iceP_taskGuid);
        }, istr -> {
            PathInfo ret;
            ret = PathInfo.ice_read(istr);
            return ret;
        });
        return f;
    }

    default PathInfo getDownloadResultZip(String taskGuid)
    {
        return getDownloadResultZip(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default PathInfo getDownloadResultZip(String taskGuid, java.util.Map<String, String> context) {
        return _iceI_getDownloadResultZipAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<PathInfo> getDownloadResultZipAsync(String taskGuid) {
        return _iceI_getDownloadResultZipAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<PathInfo> getDownloadResultZipAsync(String taskGuid, java.util.Map<String, String> context) {
        return _iceI_getDownloadResultZipAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<PathInfo> _iceI_getDownloadResultZipAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync) {
        com.zeroc.IceInternal.OutgoingAsync<PathInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getDownloadResultZip", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_taskGuid);
                 }, istr -> {
            PathInfo ret;
            ret = PathInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default SFTPInfo getFTPInfo(String taskGuid)
    {
        return getFTPInfo(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default SFTPInfo getFTPInfo(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_getFTPInfoAsync(taskGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<SFTPInfo> getFTPInfoAsync(String taskGuid)
    {
        return _iceI_getFTPInfoAsync(taskGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<SFTPInfo> getFTPInfoAsync(String taskGuid, java.util.Map<String, String> context)
    {
        return _iceI_getFTPInfoAsync(taskGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<SFTPInfo> _iceI_getFTPInfoAsync(String iceP_taskGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<SFTPInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getFTPInfo", null, sync, null);
        f.invoke(true, context, null, ostr -> {
            ostr.writeString(iceP_taskGuid);
        }, istr -> {
            SFTPInfo ret;
            ret = SFTPInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TaskPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), TaskPrx.class, _TaskPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TaskPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), TaskPrx.class, _TaskPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TaskPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), TaskPrx.class, _TaskPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TaskPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), TaskPrx.class, _TaskPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static TaskPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, TaskPrx.class, _TaskPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static TaskPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, TaskPrx.class, _TaskPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default TaskPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (TaskPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default TaskPrx ice_adapterId(String newAdapterId)
    {
        return (TaskPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default TaskPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (TaskPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default TaskPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (TaskPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default TaskPrx ice_invocationTimeout(int newTimeout)
    {
        return (TaskPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default TaskPrx ice_connectionCached(boolean newCache)
    {
        return (TaskPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default TaskPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (TaskPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default TaskPrx ice_secure(boolean b)
    {
        return (TaskPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default TaskPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (TaskPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default TaskPrx ice_preferSecure(boolean b)
    {
        return (TaskPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default TaskPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (TaskPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default TaskPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (TaskPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default TaskPrx ice_collocationOptimized(boolean b)
    {
        return (TaskPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default TaskPrx ice_twoway()
    {
        return (TaskPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default TaskPrx ice_oneway()
    {
        return (TaskPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default TaskPrx ice_batchOneway()
    {
        return (TaskPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default TaskPrx ice_datagram()
    {
        return (TaskPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default TaskPrx ice_batchDatagram()
    {
        return (TaskPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default TaskPrx ice_compress(boolean co)
    {
        return (TaskPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default TaskPrx ice_timeout(int t)
    {
        return (TaskPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default TaskPrx ice_connectionId(String connectionId)
    {
        return (TaskPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default TaskPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (TaskPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::PLS::Task";
    }
}
