// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `pls.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package top.macaulish.pls.pojo.ice;

public final class ModelsInfoHelper {
    public static void write(com.zeroc.Ice.OutputStream ostr, ModelInfo[] v) {
        if (v == null) {
            ostr.writeSize(0);
        } else {
            ostr.writeSize(v.length);
            for (int i0 = 0; i0 < v.length; i0++) {
                ModelInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static ModelInfo[] read(com.zeroc.Ice.InputStream istr) {
        final ModelInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(5);
        v = new ModelInfo[len0];
        for (int i0 = 0; i0 < len0; i0++) {
            v[i0] = ModelInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ModelInfo[]> v) {
        if (v != null && v.isPresent()) {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, ModelInfo[] v) {
        if (ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize)) {
            int pos = ostr.startSize();
            ModelsInfoHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<ModelInfo[]> read(com.zeroc.Ice.InputStream istr, int tag) {
        if (istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize)) {
            istr.skip(4);
            ModelInfo[] v;
            v = ModelsInfoHelper.read(istr);
            return java.util.Optional.of(v);
        } else {
            return java.util.Optional.empty();
        }
    }
}
