// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `pls.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package top.macaulish.pls.pojo.ice;

public class PathInfo implements Cloneable,
        java.io.Serializable {
    public static final long serialVersionUID = 1509991352L;
    private static final PathInfo _nullMarshalValue = new PathInfo();
    public String taskGuid;
    public String path;

    public PathInfo() {
        this.taskGuid = "";
        this.path = "";
    }

    public PathInfo(String taskGuid, String path) {
        this.taskGuid = taskGuid;
        this.path = path;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, PathInfo v) {
        if (v == null) {
            _nullMarshalValue.ice_writeMembers(ostr);
        } else {
            v.ice_writeMembers(ostr);
        }
    }

    static public PathInfo ice_read(com.zeroc.Ice.InputStream istr) {
        PathInfo v = new PathInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<PathInfo> v) {
        if (v != null && v.isPresent()) {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, PathInfo v) {
        if (ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize)) {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<PathInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag) {
        if (istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize)) {
            istr.skip(4);
            return java.util.Optional.of(PathInfo.ice_read(istr));
        } else {
            return java.util.Optional.empty();
        }
    }

    public boolean equals(Object rhs) {
        if (this == rhs) {
            return true;
        }
        PathInfo r = null;
        if (rhs instanceof PathInfo) {
            r = (PathInfo) rhs;
        }

        if (r != null) {
            if (this.taskGuid != r.taskGuid) {
                if (this.taskGuid == null || r.taskGuid == null || !this.taskGuid.equals(r.taskGuid)) {
                    return false;
                }
            }
            if (this.path != r.path) {
                if (this.path == null || r.path == null || !this.path.equals(r.path)) {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode() {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::PLS::PathInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskGuid);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, path);
        return h_;
    }

    public PathInfo clone() {
        PathInfo c = null;
        try {
            c = (PathInfo) super.clone();
        } catch (CloneNotSupportedException ex) {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr) {
        ostr.writeString(this.taskGuid);
        ostr.writeString(this.path);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr) {
        this.taskGuid = istr.readString();
        this.path = istr.readString();
    }
}
