// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `pls.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package top.macaulish.pls.pojo.ice;

public class TaskProcessInfo implements Cloneable,
        java.io.Serializable {
    public static final long serialVersionUID = -1833506072L;
    private static final TaskProcessInfo _nullMarshalValue = new TaskProcessInfo();
    public String taskGuid;
    public String taskState;
    public String process;

    public TaskProcessInfo() {
        this.taskGuid = "";
        this.taskState = "";
        this.process = "";
    }

    public TaskProcessInfo(String taskGuid, String taskState, String process) {
        this.taskGuid = taskGuid;
        this.taskState = taskState;
        this.process = process;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, TaskProcessInfo v) {
        if (v == null) {
            _nullMarshalValue.ice_writeMembers(ostr);
        } else {
            v.ice_writeMembers(ostr);
        }
    }

    static public TaskProcessInfo ice_read(com.zeroc.Ice.InputStream istr) {
        TaskProcessInfo v = new TaskProcessInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<TaskProcessInfo> v) {
        if (v != null && v.isPresent()) {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, TaskProcessInfo v) {
        if (ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize)) {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<TaskProcessInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag) {
        if (istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize)) {
            istr.skip(4);
            return java.util.Optional.of(TaskProcessInfo.ice_read(istr));
        } else {
            return java.util.Optional.empty();
        }
    }

    public boolean equals(Object rhs) {
        if (this == rhs) {
            return true;
        }
        TaskProcessInfo r = null;
        if (rhs instanceof TaskProcessInfo) {
            r = (TaskProcessInfo) rhs;
        }

        if (r != null) {
            if (this.taskGuid != r.taskGuid) {
                if (this.taskGuid == null || r.taskGuid == null || !this.taskGuid.equals(r.taskGuid)) {
                    return false;
                }
            }
            if (this.taskState != r.taskState) {
                if (this.taskState == null || r.taskState == null || !this.taskState.equals(r.taskState)) {
                    return false;
                }
            }
            if (this.process != r.process) {
                if (this.process == null || r.process == null || !this.process.equals(r.process)) {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode() {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::PLS::TaskProcessInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskGuid);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskState);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, process);
        return h_;
    }

    public TaskProcessInfo clone() {
        TaskProcessInfo c = null;
        try {
            c = (TaskProcessInfo) super.clone();
        } catch (CloneNotSupportedException ex) {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr) {
        ostr.writeString(this.taskGuid);
        ostr.writeString(this.taskState);
        ostr.writeString(this.process);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr) {
        this.taskGuid = istr.readString();
        this.taskState = istr.readString();
        this.process = istr.readString();
    }
}
