// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `pls.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package top.macaulish.pls.pojo.ice;

public class TaskInfo implements Cloneable,
        java.io.Serializable {
    public static final long serialVersionUID = 679540629L;
    private static final TaskInfo _nullMarshalValue = new TaskInfo();
    public String guid;
    public String state;
    public String modelGuid;
    public String modelName;
    public String totalSize;
    public String fileNumber;

    public TaskInfo() {
        this.guid = "";
        this.state = "";
        this.modelGuid = "";
        this.modelName = "";
        this.totalSize = "";
        this.fileNumber = "";
    }

    public TaskInfo(String guid, String state, String modelGuid, String modelName, String totalSize, String fileNumber) {
        this.guid = guid;
        this.state = state;
        this.modelGuid = modelGuid;
        this.modelName = modelName;
        this.totalSize = totalSize;
        this.fileNumber = fileNumber;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, TaskInfo v) {
        if (v == null) {
            _nullMarshalValue.ice_writeMembers(ostr);
        } else {
            v.ice_writeMembers(ostr);
        }
    }

    static public TaskInfo ice_read(com.zeroc.Ice.InputStream istr) {
        TaskInfo v = new TaskInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<TaskInfo> v) {
        if (v != null && v.isPresent()) {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, TaskInfo v) {
        if (ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize)) {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<TaskInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag) {
        if (istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize)) {
            istr.skip(4);
            return java.util.Optional.of(TaskInfo.ice_read(istr));
        } else {
            return java.util.Optional.empty();
        }
    }

    public boolean equals(Object rhs) {
        if (this == rhs) {
            return true;
        }
        TaskInfo r = null;
        if (rhs instanceof TaskInfo) {
            r = (TaskInfo) rhs;
        }

        if (r != null) {
            if (this.guid != r.guid) {
                if (this.guid == null || r.guid == null || !this.guid.equals(r.guid)) {
                    return false;
                }
            }
            if (this.state != r.state) {
                if (this.state == null || r.state == null || !this.state.equals(r.state)) {
                    return false;
                }
            }
            if (this.modelGuid != r.modelGuid) {
                if (this.modelGuid == null || r.modelGuid == null || !this.modelGuid.equals(r.modelGuid)) {
                    return false;
                }
            }
            if (this.modelName != r.modelName) {
                if (this.modelName == null || r.modelName == null || !this.modelName.equals(r.modelName)) {
                    return false;
                }
            }
            if (this.totalSize != r.totalSize) {
                if (this.totalSize == null || r.totalSize == null || !this.totalSize.equals(r.totalSize)) {
                    return false;
                }
            }
            if (this.fileNumber != r.fileNumber) {
                if (this.fileNumber == null || r.fileNumber == null || !this.fileNumber.equals(r.fileNumber)) {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode() {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::PLS::TaskInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, guid);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, state);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, modelGuid);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, modelName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalSize);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fileNumber);
        return h_;
    }

    public TaskInfo clone() {
        TaskInfo c = null;
        try {
            c = (TaskInfo) super.clone();
        } catch (CloneNotSupportedException ex) {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr) {
        ostr.writeString(this.guid);
        ostr.writeString(this.state);
        ostr.writeString(this.modelGuid);
        ostr.writeString(this.modelName);
        ostr.writeString(this.totalSize);
        ostr.writeString(this.fileNumber);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr) {
        this.guid = istr.readString();
        this.state = istr.readString();
        this.modelGuid = istr.readString();
        this.modelName = istr.readString();
        this.totalSize = istr.readString();
        this.fileNumber = istr.readString();
    }
}
