// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `pls.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package top.macaulish.pls.ice.client;

public interface ModelPrx extends com.zeroc.Ice.ObjectPrx
{
    default String getAll()
    {
        return getAll(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getAll(java.util.Map<String, String> context)
    {
        return _iceI_getAllAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String> getAllAsync()
    {
        return _iceI_getAllAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String> getAllAsync(java.util.Map<String, String> context)
    {
        return _iceI_getAllAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<String> _iceI_getAllAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getAll", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String getSpecific(String modelGuid)
    {
        return getSpecific(modelGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getSpecific(String modelGuid, java.util.Map<String, String> context)
    {
        return _iceI_getSpecificAsync(modelGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String> getSpecificAsync(String modelGuid)
    {
        return _iceI_getSpecificAsync(modelGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String> getSpecificAsync(String modelGuid, java.util.Map<String, String> context)
    {
        return _iceI_getSpecificAsync(modelGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<String> _iceI_getSpecificAsync(String iceP_modelGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getSpecific", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_modelGuid);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default boolean startup(String modelGuid)
    {
        return startup(modelGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean startup(String modelGuid, java.util.Map<String, String> context)
    {
        return _iceI_startupAsync(modelGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Boolean> startupAsync(String modelGuid)
    {
        return _iceI_startupAsync(modelGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Boolean> startupAsync(String modelGuid, java.util.Map<String, String> context)
    {
        return _iceI_startupAsync(modelGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Boolean> _iceI_startupAsync(String iceP_modelGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_modelGuid);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean shutdown(String modelGuid)
    {
        return shutdown(modelGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean shutdown(String modelGuid, java.util.Map<String, String> context)
    {
        return _iceI_shutdownAsync(modelGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Boolean> shutdownAsync(String modelGuid)
    {
        return _iceI_shutdownAsync(modelGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Boolean> shutdownAsync(String modelGuid, java.util.Map<String, String> context)
    {
        return _iceI_shutdownAsync(modelGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Boolean> _iceI_shutdownAsync(String iceP_modelGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "shutdown", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_modelGuid);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean reStartup(String modelGuid)
    {
        return reStartup(modelGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean reStartup(String modelGuid, java.util.Map<String, String> context)
    {
        return _iceI_reStartupAsync(modelGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Boolean> reStartupAsync(String modelGuid)
    {
        return _iceI_reStartupAsync(modelGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Boolean> reStartupAsync(String modelGuid, java.util.Map<String, String> context)
    {
        return _iceI_reStartupAsync(modelGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Boolean> _iceI_reStartupAsync(String iceP_modelGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "reStartup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_modelGuid);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default int consumeAbilicy(String modelGuid)
    {
        return consumeAbilicy(modelGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int consumeAbilicy(String modelGuid, java.util.Map<String, String> context)
    {
        return _iceI_consumeAbilicyAsync(modelGuid, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Integer> consumeAbilicyAsync(String modelGuid)
    {
        return _iceI_consumeAbilicyAsync(modelGuid, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Integer> consumeAbilicyAsync(String modelGuid, java.util.Map<String, String> context)
    {
        return _iceI_consumeAbilicyAsync(modelGuid, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Integer> _iceI_consumeAbilicyAsync(String iceP_modelGuid, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "consumeAbilicy", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_modelGuid);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ModelPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ModelPrx.class, _ModelPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ModelPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ModelPrx.class, _ModelPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ModelPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ModelPrx.class, _ModelPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ModelPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ModelPrx.class, _ModelPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ModelPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ModelPrx.class, _ModelPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ModelPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ModelPrx.class, _ModelPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ModelPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ModelPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ModelPrx ice_adapterId(String newAdapterId)
    {
        return (ModelPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ModelPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ModelPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ModelPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ModelPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ModelPrx ice_invocationTimeout(int newTimeout)
    {
        return (ModelPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ModelPrx ice_connectionCached(boolean newCache)
    {
        return (ModelPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ModelPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ModelPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ModelPrx ice_secure(boolean b)
    {
        return (ModelPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ModelPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ModelPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ModelPrx ice_preferSecure(boolean b)
    {
        return (ModelPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ModelPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ModelPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ModelPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ModelPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ModelPrx ice_collocationOptimized(boolean b)
    {
        return (ModelPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ModelPrx ice_twoway()
    {
        return (ModelPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ModelPrx ice_oneway()
    {
        return (ModelPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ModelPrx ice_batchOneway()
    {
        return (ModelPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ModelPrx ice_datagram()
    {
        return (ModelPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ModelPrx ice_batchDatagram()
    {
        return (ModelPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ModelPrx ice_compress(boolean co)
    {
        return (ModelPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ModelPrx ice_timeout(int t)
    {
        return (ModelPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ModelPrx ice_connectionId(String connectionId)
    {
        return (ModelPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ModelPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ModelPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::PLS::Model";
    }
}
